[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1


[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']


[[plugins]]
repo = 'ponko2/deoplete-fish'
on_ft = ['fish']
depends = ['deoplete.nvim']


[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
depends = ['deoplete.nvim']


[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete.nvim']


[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
hook_source = '''
  if system('echo -n $SHELL') =~ "fish$"
    let g:deoplete#sources#clang#libclang_path = system('echo -n (find / -name libclang.so -or -name libclang.so.1 2> /dev/null | head -n 1)')
  else
    let g:deoplete#sources#clang#libclang_path = system('echo -n $(find / -name libclang.so -or -name libclang.so.1 2> /dev/null | head -n 1)')
  endif

  let g:deoplete#sources#clang#clang_header = /usr/lib/clang
'''
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']


[[plugins]]
repo = 'landaire/deoplete-swift'
hook_source = '''
  let g:deoplete#sources#swift#daemon_autostart = 1
'''
on_ft = ['swift']
depends = ['deoplete.nvim']


[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']
depends = ['deoplete.nvim']

#[[plugins]]
#repo = 'andviro/flake8-vim'
#on_ft = ['python']
#
#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'
#on_ft = ['python']
#
#[[plugins]]
#repo = 'keith/swift.vim'
